### PR TITLE
mobile/tablet menu-button (hamburger)

### PR DESCRIPTION
**Pull request by katiadobra**
http://katiadobra.github.io/12332-Pink/

### CODE REVIEW

**Comment by katiadobra** [comment]
Task complete thanks to @aalexeev239

**Comment by aalexeev239** [comment]
@katiadobra roger that

**Comment by katiadobra** [comment]
@aalexeev239 
what's new:
- slick slider added;
- main-header and main-footer logos are on SVG now;
- main-footer socials;
- clean task and cmq task added to Gruntfile

**Comment by katiadobra** [comment]
@aalexeev239 
optimization task

**Pull request merged**
